[project]
name = "testllm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docx2pdf>=0.1.8",
    "dotenv>=0.9.9",
    "google-genai>=1.48.0",
    "gradio>=5.49.1",
    "pandas>=2.3.3"
]
